### ISSUE TITLE
The listing of constants is not properly documented

### ISSUE THREAD

**Issue by tzeroem** [mariotoffia/goasciidoc#16] opened 2021-12-03 16:36 UTC
The listing of constants is not properly documented

```go
const (
	AuthorizeRemoteTxRequests string = "AuthorizeRemoteTxRequests"
	ClockAlignedDataInterval  string = "ClockAlignedDataInterval"
	ConnectionTimeOut         string = "ConnectionTimeOut"
	ConnectorPhaseRotation    string = "ConnectorPhaseRotation"
	GetConfigurationMaxKeys   string = "GetConfigurationMaxKeys"
	HeartbeatInterval         string = "HeartbeatInterval"
	LocalAuthorizeOffline     string = "LocalAuthorizeOffline"
	LocalPreAuthorize         string = "LocalPreAuthorize"
)
```

![image](https://user-images.githubusercontent.com/11984092/144638173-311cf55f-9e62-40f9-b522-2388843de450.png)

Adding a comment to the const group leads to multiple calls
```go
// This is not Working
const (
	AuthorizeRemoteTxRequests string = "AuthorizeRemoteTxRequests"
	ClockAlignedDataInterval  string = "ClockAlignedDataInterval"
	ConnectionTimeOut         string = "ConnectionTimeOut"
	ConnectorPhaseRotation    string = "ConnectorPhaseRotation"
	GetConfigurationMaxKeys   string = "GetConfigurationMaxKeys"
	HeartbeatInterval         string = "HeartbeatInterval"
	LocalAuthorizeOffline     string = "LocalAuthorizeOffline"
	LocalPreAuthorize         string = "LocalPreAuthorize"
)
```
![image](https://user-images.githubusercontent.com/11984092/144638508-1486336e-543d-429b-bad9-a76290ab2d76.png)

**Comment by mariotoffia** [comment] 2021-12-04 22:53
Thanks, @tzeroem, for reporting this.

**Comment by mariotoffia** [comment] 2021-12-04 23:15
Hi @tzeroem, I'm sorry but I cannot reproduce your problem. Could you please give me a simple go project that reproduce this problem?

Your first example (with documentation) is e.g. rendered [here](https://github.com/mariotoffia/goasciidoc/blob/master/docs.adoc#constants). I've also tried to add a comment above the const in the file (and rendered the solution) and it treats the comment as unbounded but the const is still rendering correctly.

Oh, are you using the default templates for render or have you customized those?

Cheers,
 Mario :)

**Comment by mariotoffia** [comment] 2021-12-15 06:01
Hi @tzeroem, have you yet found some time to give me some feedback? Otherwise I'll close this issue and if you come back later and the problem still persists. I'll just open it again.

Cheers,
 Mario :)

**Closed as completed by mariotoffia** 2021-12-15 06:01 UTC
Labels: Investigate, waiting
